# permissions for end users to view cis.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/instance: ci-viewer-role
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: knci
    app.kubernetes.io/part-of: knci
    app.kubernetes.io/managed-by: kustomize
  name: ci-viewer-role
rules:
- apiGroups:
  - ci.knci
  resources:
  - cis
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - ci.knci
  resources:
  - cis/status
  verbs:
  - get
